services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  actions:
    build:
      context: .
      dockerfile: docker/micro/Dockerfile
      args:
        PROJECT_DIR: micros/actions
        PROJECT_NAMESPACE: Actions
        PORT: 5001
    container_name: actions
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=ActionDb
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  profile:
    build:
      context: .
      dockerfile: docker/micro/Dockerfile
      args:
        PROJECT_DIR: micros/profile
        PROJECT_NAMESPACE: Profile
        PORT: 5002
    container_name: profile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=ActionDb
    ports:
      - "5002:5002"
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./init-nginx.sh:/docker-entrypoint.d/init-nginx.sh:ro
      - ./certs:/etc/nginx/certs:rw
    entrypoint: ["/docker-entrypoint.d/init-nginx.sh"]
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
    depends_on:
      - profile
      - actions

volumes:
  mongo-data:
